# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sawi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brief', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('datePosted', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='about',
            field=models.TextField(default='About the instituttion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='motto',
            field=models.CharField(default='Motto', max_length=100),
            preserve_default=False,
        ),
    ]
