# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2016-06-14 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Sawi', '0002_auto_20180303_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2016, 6, 14, 15, 46, 38, 90595, tzinfo=utc), max_length=20, verbose_name='Firstname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='Adewale', max_length=20, verbose_name='Lastname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=15, verbose_name='Sex'),
        ),
    ]
