# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2016-06-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sawi', '0003_auto_20160614_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='Adewale', max_length=20, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='Johnson', max_length=20, verbose_name='Lastname'),
        ),
    ]
